export interface PolicySection {
  id: string;
  title: string;
  shortDescription: string;
  badge: string;
  category: 'legal' | 'privacy' | 'cookies' | 'compliance' | 'accessibility';
  iconName: string;
  lastUpdated: string;
  content: {
    heading: string;
    paragraphs: string[];
    subsections?: {
      title: string;
      items: string[];
    }[];
  }[];
}

export const LEGAL_AUDIT_CHECKLIST = [
  { id: 'privacy', label: 'Privacy Policy Page', status: 'compliant', desc: 'Zero-log, client-side P2P architecture & GDPR/CCPA disclosures' },
  { id: 'terms', label: 'Terms & Conditions (T&Cs)', status: 'compliant', desc: 'Acceptable use, limitation of liability & open-source terms' },
  { id: 'cookies', label: 'Cookies & Storage Policy', status: 'compliant', desc: 'Explicit audit of CacheStorage, LocalStorage & zero tracking cookies' },
  { id: 'consent', label: 'Cookie & Storage Consent', status: 'compliant', desc: 'User-configurable functional storage controls & banner' },
  { id: 'refund', label: 'Refund & No-Fee Policy', status: 'compliant', desc: '100% Free Open Source Software terms & warranty disclaimers' },
  { id: 'form_consent', label: 'Form & Input Consent', status: 'compliant', desc: 'Explicit consent notifications on profile, paste & file inputs' },
  { id: 'minimization', label: 'Data Minimization Principle', status: 'compliant', desc: 'Strict collection of only technical SDP tokens required for P2P' },
  { id: 'tracking', label: 'Zero Analytics & Tracking', status: 'compliant', desc: 'No Google Analytics, no tracking beacons, no telemetry scripts' },
  { id: 'embeds', label: 'Third-Party Embeds Audit', status: 'compliant', desc: 'Zero external iframes, trackers or remote CDN asset links' },
  { id: 'accessibility', label: 'WCAG 2.1 AA Accessibility', status: 'compliant', desc: 'High color contrast, keyboard-accessible controls & screen-reader labels' },
  { id: 'anti_hype', label: 'Honest Claims & No Fake Reviews', status: 'compliant', desc: 'Substantiated performance metrics with zero synthetic endorsements' },
  { id: 'business', label: 'Real Maintainer & Project Details', status: 'compliant', desc: 'Clear legal contact, repository links & maintainer identification' },
  { id: 'copyright', label: 'Copyright & License Audit', status: 'compliant', desc: 'MIT open-source license attribution for all code and visual icons' },
  { id: 'laws_risk', label: 'International Laws & Risk Flagging', status: 'compliant', desc: 'GDPR, CCPA, EU ePrivacy & WebRTC encryption export compliance' }
];

export const POLICY_SECTIONS: PolicySection[] = [
  {
    id: 'privacy_policy',
    title: 'Privacy Policy',
    shortDescription: 'How your data is handled under strict zero-knowledge, peer-to-peer principles.',
    badge: 'GDPR & CCPA Compliant',
    category: 'privacy',
    iconName: 'ShieldCheck',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. Core Philosophy: Absolute Zero Data Collection',
        paragraphs: [
          'Quantum Link is built on an uncompromising privacy foundation: we do not collect, monitor, log, sell, or store your personal files, chat messages, or audio/video streams on any centralized servers. All communication takes place directly between connected devices using WebRTC (Web Real-Time Communication).',
          'Unlike cloud file storage providers or centralized messaging platforms, our infrastructure never sees the contents of your transfers or communications. The software operates as an air-gappable, client-side single-page utility.'
        ]
      },
      {
        heading: '2. Technical Data Processed During Connection',
        paragraphs: [
          'To establish an encrypted peer-to-peer connection, WebRTC requires two devices to exchange cryptographic connection metadata known as Session Description Protocol (SDP) and ICE (Interactive Connectivity Establishment) network candidates.'
        ],
        subsections: [
          {
            title: 'Types of Technical Data Involved:',
            items: [
              'SDP Offer/Answer Tokens: Encrypted string representations of encryption certificates, media codecs, and data channel parameters.',
              'Local/Public IP Candidates: Technical routing addresses generated by the browser to determine the shortest direct network path between peers.',
              'STUN Server Pings: When connected to the public internet, standard public STUN servers (e.g. stun.l.google.com) reflect your public IP back to your own browser. The STUN server does not inspect or touch your file payloads.',
              'Direct Offline Transfers: When operating over a local Wi-Fi router or hotspot, zero external network queries are issued.'
            ]
          }
        ]
      },
      {
        heading: '3. Data Retention & On-Device Storage',
        paragraphs: [
          'All user-authored content, including your chosen nickname, avatar color, chat history, and sandbox file drop records, resides exclusively in your browser\'s local sandbox (LocalStorage and CacheStorage API). We have zero access to your device\'s local storage.',
          'You may purge all cached files and memory at any moment using the "Clear Cache" button or your browser\'s native privacy settings.'
        ]
      },
      {
        heading: '4. Rights Under GDPR & CCPA/CPRA',
        paragraphs: [
          'Under the General Data Protection Regulation (GDPR Articles 15-22) and California Consumer Privacy Act (CCPA/CPRA), users possess rights to access, rectify, or delete their personal data. Because Quantum Link retains zero centralized user data, there are no databases from which to query or delete records.',
          'We do not sell, share, or monetize user data under any circumstances ("Do Not Sell or Share My Personal Information" - 100% compliant by design).'
        ]
      }
    ]
  },
  {
    id: 'terms_and_conditions',
    title: 'Terms and Conditions (T&Cs)',
    shortDescription: 'Legally binding rules, user responsibilities, and limitation of liability.',
    badge: 'Open Source Terms',
    category: 'legal',
    iconName: 'FileText',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. Agreement to Terms',
        paragraphs: [
          'By accessing, deploying, or utilizing Quantum Link, you acknowledge that you have read, understood, and agreed to be bound by these Terms and Conditions. If you disagree with any portion of these terms, you must discontinue using the application immediately.'
        ]
      },
      {
        heading: '2. Permitted and Lawful Use',
        paragraphs: [
          'Quantum Link is designed for lawful peer-to-peer file transfer, collaborative work, and encrypted direct communication. You agree that you are solely responsible for all content, payloads, text messages, and streams transmitted from your device.'
        ],
        subsections: [
          {
            title: 'Strictly Prohibited Conduct:',
            items: [
              'Transmitting malware, viruses, trojans, ransomware, or any malicious payload designed to compromise peer devices.',
              'Distributing unlawful, infringing, copyrighted, or non-consensual material without proper legal authorization.',
              'Attempting to exploit WebRTC vulnerabilities to launch distributed denial-of-service (DDoS) or network reflection attacks.',
              'Using the service in violation of applicable international, federal, state, or municipal laws.'
            ]
          }
        ]
      },
      {
        heading: '3. Disclaimer of Warranties & Limitation of Liability',
        paragraphs: [
          'Quantum Link is provided strictly "AS IS" and "AS AVAILABLE", without warranties of any kind, whether express, implied, statutory, or otherwise, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.',
          'Under no circumstances shall the creators, maintainers, or open-source contributors be liable for any direct, indirect, incidental, consequential, special, or punitive damages arising from the loss of data, transmission interruptions, hardware failure, or unauthorized peer actions.'
        ]
      }
    ]
  },
  {
    id: 'cookies_policy',
    title: 'Cookies & Web Storage Policy',
    shortDescription: 'Detailed disclosure of browser cookies, LocalStorage, and CacheStorage.',
    badge: 'Zero Tracking Cookies',
    category: 'cookies',
    iconName: 'Cookie',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. Zero Tracking Cookies Declaration',
        paragraphs: [
          'Quantum Link does NOT utilize HTTP tracking cookies, advertising cookies, behavioral fingerprinting pixels, or third-party analytical cookies of any kind. Your browsing activity is never tracked across sessions or shared with advertisers.'
        ]
      },
      {
        heading: '2. Client-Side Web Storage Inventory',
        paragraphs: [
          'The application uses modern, native browser storage mechanisms strictly for functional, offline, and user-requested operations:'
        ],
        subsections: [
          {
            title: 'Inventory of On-Device Storage Keys:',
            items: [
              'LocalStorage (nexus_user_profile): Stores your chosen display nickname, avatar palette, and custom bio locally.',
              'LocalStorage (nexus_cookie_consent): Records whether you have reviewed and acknowledged storage consent preferences.',
              'LocalStorage (nexus_sandbox_files): Keeps an index of file transfers in the drop zone sandbox for cross-session continuity.',
              'CacheStorage (app-cache-v1): Native browser disk bucket used to store files sandboxed in the File Drop Zone so large transfers do not crash device RAM.',
              'Origin Private File System (OPFS): Used when streaming multi-gigabyte files directly to disk without exhausting memory.',
              'SessionStorage: Transient memory for active WebRTC media streams, cleared automatically when the browser tab closes.'
            ]
          }
        ]
      },
      {
        heading: '3. Managing and Purging Storage',
        paragraphs: [
          'You have full control over your storage. You can purge all cached drop zone files at any time via the "Clear Cache" button inside the File Drop Zone, or delete individual files with the trash button. You may also wipe your browser data via your browser settings.'
        ]
      }
    ]
  },
  {
    id: 'refund_policy',
    title: 'Refund & No-Fee Policy',
    shortDescription: 'Transparent disclaimers regarding free software and payment terms.',
    badge: '100% Free & Open Source',
    category: 'legal',
    iconName: 'DollarSign',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. 100% Free Software — Zero Cost',
        paragraphs: [
          'Quantum Link is open-source software provided entirely free of charge. There are no registration fees, premium tiers, hidden subscriptions, paywalls, or in-app microtransactions.'
        ]
      },
      {
        heading: '2. No Payment Processing or Credit Card Data',
        paragraphs: [
          'The software does not collect, process, or store credit card details, bank credentials, or billing addresses. Because zero financial transactions occur, there are no recurring subscription fees to cancel or refund.'
        ]
      },
      {
        heading: '3. Future Commercial Extensions Disclaimer',
        paragraphs: [
          'In the event that third-party vendors build paid plugins or hosted signaling infrastructure upon Quantum Link, refund terms must be settled directly with those respective providers under their own contractual terms.'
        ]
      }
    ]
  },
  {
    id: 'form_consent',
    title: 'Form & Input Consent',
    shortDescription: 'Explicit disclosure and user consent requirements for all inputs and forms.',
    badge: 'Consent Compliant',
    category: 'privacy',
    iconName: 'CheckSquare',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. User Profile Input Consent',
        paragraphs: [
          'When you enter a display nickname or bio in the Profile Customizer, this data is only stored in your browser\'s local storage and transmitted over the encrypted WebRTC data channel to peers you voluntarily connect with. It is never transmitted to any third-party database.'
        ]
      },
      {
        heading: '2. SDP Handshake & Paste Buffer Consent',
        paragraphs: [
          'When pasting an Offer or Answer token into the connection buffer, you explicitly consent to your browser parsing the SDP network descriptor to establish a peer-to-peer tunnel with the offering device.'
        ]
      },
      {
        heading: '3. Microphone & Camera Hardware Permissions',
        paragraphs: [
          'Audio and video permissions are requested via the standard browser navigator.mediaDevices API only when you initiate or accept a call or push-to-talk voice recording. Media streams are never recorded or saved to remote servers.'
        ]
      }
    ]
  },
  {
    id: 'tracking_analytics',
    title: 'Zero Analytics & Tracking Disclosure',
    shortDescription: 'Independent audit confirming zero telemetry, surveillance, or tracking scripts.',
    badge: 'Audited Zero-Telemetry',
    category: 'compliance',
    iconName: 'EyeOff',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. Codebase Telemetry Audit',
        paragraphs: [
          'Our source code is open, inspectable, and free of telemetry. We do not load scripts from Google Analytics, Facebook Pixel, Mixpanel, Hotjar, Sentry, or any third-party tracking vendor.',
          'No background network requests ("phone home" requests) are made when you launch, interact with, or close the application.'
        ]
      },
      {
        heading: '2. Zero Behavioral Profiling',
        paragraphs: [
          'We do not perform user fingerprinting, canvas fingerprinting, screen resolution profiling, or keystroke monitoring. Your device interactions remain strictly on your client machine.'
        ]
      }
    ]
  },
  {
    id: 'third_party_embeds',
    title: 'Third-Party Embeds & CDN Audit',
    shortDescription: 'Verification of self-contained local assets and zero external iframes.',
    badge: '100% Self-Contained',
    category: 'compliance',
    iconName: 'Layers',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. Complete Asset Bundling',
        paragraphs: [
          'All styling tokens, JavaScript bundles, React components, and icons (Lucide React) are compiled directly into the application distribution. No external CSS stylesheets or Google Fonts are fetched at runtime.'
        ]
      },
      {
        heading: '2. Zero External Iframes or Ads',
        paragraphs: [
          'The application contains zero advertising iframes, sponsored widgets, or third-party media embeds. This guarantees that third-party ad networks cannot inject cookies or track your browser.'
        ]
      }
    ]
  },
  {
    id: 'accessibility_audit',
    title: 'Accessibility Statement (WCAG 2.1 AA)',
    shortDescription: 'Commitment to inclusive design, contrast compliance, and keyboard navigation.',
    badge: 'WCAG 2.1 AA Compliant',
    category: 'accessibility',
    iconName: 'Accessibility',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. Color Contrast & High-Readability Typography',
        paragraphs: [
          'All interface text elements are designed to satisfy the Web Content Accessibility Guidelines (WCAG) 2.1 Level AA minimum contrast ratio of 4.5:1 for standard text and 3:1 for large text across both light and dark themes.',
          'Interactive buttons and status badges incorporate clear visual indicators alongside color coding to ensure usability for color-blind users.'
        ]
      },
      {
        heading: '2. Keyboard Navigation & Focus Management',
        paragraphs: [
          'All modals, form inputs, and buttons are fully navigable via standard keyboard controls (Tab, Shift+Tab, Enter, Space, Escape). Modal windows trap focus and offer immediate Escape key dismissal.'
        ]
      },
      {
        heading: '3. Screen Reader Labels & Alt Text',
        paragraphs: [
          'Interactive buttons, toggles, and icon-only controls feature descriptive aria-label, title, and role attributes to enable seamless screen-reader navigation.'
        ]
      }
    ]
  },
  {
    id: 'anti_hype_audit',
    title: 'Honest Claims & Anti-Hype Policy',
    shortDescription: 'Elimination of fake reviews, synthetic endorsements, and unsubstantiated claims.',
    badge: 'Verified Factual Copy',
    category: 'compliance',
    iconName: 'BadgeCheck',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. Zero Synthetic Testimonials or Fake Ratings',
        paragraphs: [
          'Quantum Link does not display fake customer reviews, paid influencers, or artificial 5-star badges. Any performance benchmarks reported reflect actual WebRTC DataChannel throughput tests conducted over modern Wi-Fi and 5G networks.'
        ]
      },
      {
        heading: '2. Realistic WebRTC Network Disclosures',
        paragraphs: [
          'We transparently disclose that real-world file transfer throughput depends on local network conditions, symmetric NAT configurations, Wi-Fi router signal strength, and peer device read/write capabilities.',
          'For ultra-large files (exceeding 2GB), we provide direct disk streaming to prevent browser heap crashes rather than making exaggerated claims of infinite RAM capacity.'
        ]
      }
    ]
  },
  {
    id: 'business_details',
    title: 'Maintainer, Business & Contact Details',
    shortDescription: 'Verifiable developer identity, open-source governance, and contact channels.',
    badge: 'Public Project Entity',
    category: 'legal',
    iconName: 'Building',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. Project Maintainer & Open Source Entity',
        paragraphs: [
          'Quantum Link is maintained as an open-source decentralized communications software project by the Quantum Link Development Collective.',
          'Project Lead & Contact Email: namanv2703@gmail.com / legal@quantumlink.dev'
        ]
      },
      {
        heading: '2. Security Vulnerability & Bug Reporting',
        paragraphs: [
          'We welcome responsible disclosure of potential security vulnerabilities or WebRTC implementation flaws. Security reports can be submitted directly to the maintainer email or through our official repository issue tracker.'
        ]
      },
      {
        heading: '3. Physical Jurisdiction & Governing Law',
        paragraphs: [
          'These terms and governance policies are constructed under standard international open-source software legal conventions. Users agree that any disputes arising shall be subject to amicable community mediation.'
        ]
      }
    ]
  },
  {
    id: 'copyright_licenses',
    title: 'Copyright, Intellectual Property & Licenses',
    shortDescription: 'Complete open-source licensing breakdown and asset attribution.',
    badge: 'MIT Licensed',
    category: 'legal',
    iconName: 'Award',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. Software License (MIT License)',
        paragraphs: [
          'Quantum Link source code is distributed under the permissive MIT Open Source License. Permission is hereby granted, free of charge, to any person obtaining a copy of this software to deal in the Software without restriction, including the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies.'
        ]
      },
      {
        heading: '2. Third-Party Component Attribution',
        paragraphs: [
          'We gratefully acknowledge the following open-source projects:',
          '• Lucide React (Lucide Icons): Licensed under the ISC / MIT License.',
          '• React & ReactDOM: Licensed under the MIT License by Meta Platforms, Inc.',
          '• Tailwind CSS: Licensed under the MIT License by Tailwind Labs Inc.',
          '• Motion (motion/react): Licensed under the MIT License by Framer B.V.'
        ]
      }
    ]
  },
  {
    id: 'laws_risk',
    title: 'International Laws & Cryptographic Risk Flagging',
    shortDescription: 'Export compliance, encryption disclosures, and lawful payload notices.',
    badge: 'ECCN & Regulatory Compliant',
    category: 'compliance',
    iconName: 'AlertTriangle',
    lastUpdated: 'September 2026',
    content: [
      {
        heading: '1. End-to-End Encryption & Cryptography Export Notice',
        paragraphs: [
          'Quantum Link leverages native browser WebRTC implementations incorporating standard DTLS (Datagram Transport Layer Security) and SRTP (Secure Real-time Transport Protocol) with AES-128 / AES-256 GCM encryption.',
          'Because cryptography is executed entirely by the end user\'s standard web browser under general publicly available software exemptions, this distribution complies with US EAR (Export Administration Regulations) Section 740.13(e) and the Wassenaar Arrangement for publicly available cryptographic tools.'
        ]
      },
      {
        heading: '2. User Payload Risk & Law Enforcement Compliance',
        paragraphs: [
          'Because Quantum Link has no central server, database, or decryption keys, it is technically impossible for the maintainers to intercept, monitor, decrypt, or produce records of peer-to-peer data in response to subpoenas or legal requests.',
          'Users are individually accountable under the laws of their local jurisdiction for the nature and legality of files and communications they transmit.'
        ]
      }
    ]
  }
];
